base_url = "https://xulin.me"
title = "(b (s x g))"

output_dir = "docs"
compile_sass = true
build_search_index = true

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
highlight_theme = "inspired-github"

[extra]
# Put all your custom variables here
date_format = "%d / %m / %Y"
hometitle = "部署小歌"
homeSubtitle = "穷且益坚 不坠青云之志"
#homeSubtitle = "窮且益堅, 不墜青雲之志"
