base_url = "https://www.0x10086.com"
title = "(Re (S a n))"

output_dir = "docs"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = false
highlight_theme = "inspired-github"

[extra]
date_format = "%d / %m / %Y"
hometitle = "部署小歌"
homeSubtitle = "穷且益坚，不坠青云之志"
