baseurl: ""
title: b-s-x-g
languageCode: en-us
theme: hello-friend-ng
paginate: 19
publishDir: docs
Author:
  name: xuls
params:
  dateform: 'Jan 2, 2006'
  dateformShort: '1 / 02 / 2006'
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04'
  homeSubtitle: 窮且益堅, 不墜青雲之志.
  disableReadOtherPosts: false
  enableSharingButtons: false
  description: My new homepage or blog
  keywords: 'homepage, blog'
  footerRight: ' '
  footerLeft: ' '
  images:
    - ''
#Default theme "light" or "dark"
  defaultTheme: light
taxonomies:
  category: blog
  tag: tags
  series: series
languages:
  en:
    title: 部署小歌
    subtitle: ""
    keywords: ''
#    copyright: >-
#      <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
#      rel="noopener">CC BY-NC 4.0</a>
    readOtherPosts: Read other posts
    disableKinds: RSS
    params:
      logo:
        logoText: (b (s x g))
        logoHomeLink: /
menu:
  main:
  - identifier: blog
    name: 博客
    url: /blog
  - identifier: weekly
    name: 週刊
    url: /weekly
#  - identifier: cs
#    name: 編碼
#    url: /cs
#  - identifier: echo
#    name: 雜談
#    url: /echo
