name: static

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: docs
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
